import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button'
import Card from '@mui/material/Card'
import CardContent from '@mui/material/CardContent'
import Grid from '@mui/material/Grid'
import DownloadRoundedIcon from '@mui/icons-material/DownloadRounded';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
        <title>Disbot Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span className={styles.gradtitle}>Disbot</span> Website! :D
        </h1>
        <p className={styles.subtitle}>Download and start coding with our bot with <span className={styles.code}>discord.py</span></p>
        <br></br>
        <Button variant="contained" startIcon={<DownloadRoundedIcon />}><a href="https://github.com/Valenplayer3000/Disbot/archive/refs/tags/Stable-0.1.zip"> Download Disbot v0.1</a></Button>
        <p className={styles.description}>New, Simple and Fun! </p>
        
        
        <Grid container   direction="column" justifyContent="center" alignItems="stretch">
        <Card>
          <CardContent>
            <h2>New.</h2>
            <p>The Bot is new, so they are ready to use.</p>
          </CardContent>
        </Card>
      <br></br>
        <Card>
          <CardContent>
            <h2>Simple. </h2>
            <p>The bot is made simple. Using python and Discord.py!</p>
          </CardContent>
        </Card>
      <br></br>
        <Card>
          <CardContent>
            <h2>Fun.</h2>
            <p>This bot is so Fun. So you can use these joke commands (Like ban and kick commands)</p>
          </CardContent>
        </Card>
      <br></br>
        <Card>
          <CardContent>
            <h2>Modify.</h2>
            <p>This bot can be forked thanks to open source.</p>
          </CardContent>
        </Card>
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered and Thanks to Material UI and {' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
