import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span className={styles.gradtitle}>Disbot</span> Website! :D
        </h1>
        <p className={styles.subtitle}>Download and start coding with our bot with <span className={styles.code}>discord.py</span></p>
          <button className={styles.btn} type="submit"><a href="https://github.com/Valenplayer3000/Disbot/archive/refs/tags/Stable-0.1.zip">Download Disbot v0.1</a></button>
        <p className={styles.description}>New, Simple and Fun! </p>
        

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>New.</h2>
            <p>The Bot are new, so they are ready to use.</p>
          </div>

          <div  className={styles.card}>
            <h2>Simple. </h2>
            <p>The bot is made simple. Using with python and Discord.py!</p>
          </div>

          <div className={styles.card}>
            <h2>Fun.</h2>
            <p>This bot is so Fun. So you can use these joke commands (Like ban and kick commands)</p>
          </div>

          <div
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Modify.</h2>
            <p>
              This bot can be forked thanks of open source.
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered and Thanks to {' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
